### ISSUE TITLE
Lighthouse browser script error

### ISSUE THREAD

**Issue by princhonzik** [bozdoz/wp-plugin-leaflet-map#103]
I get an error in Google Lighthouse on a live webpage:

TypeError: t.splice is not a function at /wp-content/plugins/leaflet-map/scripts/construct-leaflet-map.min.js?ver=2.15.0:1:1784 at /wp-content/plugins/leaflet-map/scripts/construct-leaflet-map.min.js?ver=2.15.0:1:2023

Sorry if this is not relevant or an issue on my side; I have no expertise in Javascript and do not know what this means, please excuse that. Any ideas? Thanks.

**Comment by bozdoz** [comment]
Is the plugin working? Or is this just a warning from Google Lighthouse?

**Comment by princhonzik** [comment]
Everything seems to be okay as far as I tried.

**Comment by bozdoz** [comment]
I can't even get lighthouse to work; keep hitting this issue: https://github.com/GoogleChrome/lighthouse/issues/9484

**Comment by princhonzik** [comment]
https://web.dev/measure/ I used their web.dev thing, is that an option?

**Comment by bozdoz** [comment]
I am only testing on localhost; I haven't tried putting it on a site and testing yet. Could maybe later; seems like it's an issue with my browser, or Lighthouse.

**Comment by bozdoz** [comment]
I'm going to close this due to inactivity.  If you found a specific issue, or a solution, please reopen.
