### ISSUE TITLE
Use leaflet variables in attributes?

### ISSUE THREAD

**Issue by bozdoz** [bozdoz/wp-plugin-leaflet-map#108]
https://wordpress.org/support/topic/parameter-dragging/

e.g. [leaflet-map dragging="!L.Browser.mobile"]

**Comment by b-pfl** [comment]
Sounds much appreciated! 
Probably an option dragging=[yes|no|noMobile] would be best...

**Comment by bozdoz** [comment]
Added new [liquid-like](https://shopify.github.io/liquid/filters/upcase/) syntax for raw JavaScript:

`[leaflet-map dragging="{!L.Browser.mobile | raw}"]`

If using Gutenburg, you must use a **shortcode block**!  Otherwise it won't parse the value properly.
