### ISSUE TITLE
Leaflet Map admin menu entry conflicts with All In One WP Security plugin

### ISSUE THREAD

**Issue by ziodave** [bozdoz/wp-plugin-leaflet-map#11]
Hello,

By chance I found out that when I activate the Leaflet Map plugin, the admin entry for All In One WP Security plugin disappears.

I opened an issue also on the [All In One WP Security](https://github.com/Arsenal21/all-in-one-wordpress-security/issues/7) plugin.

I hope this can be solved.

BR
David

**Comment by bozdoz** [comment]
Thanks for the heads up. It's been fixed!
