### ISSUE TITLE
Zoom >18 doesn't work

### ISSUE THREAD

**Issue by ferdi2005** [bozdoz/wp-plugin-leaflet-map#110]
Zoom with the zoom controls globally activated >18 (you see from the gif, it starts at 17, 18 works >18 doesn't work) doesn't work and generate a wrong grey screen!

![](https://user-images.githubusercontent.com/19609180/87816170-2e2b5580-c867-11ea-8183-ad623d61b200.gif)

**Comment by bozdoz** [comment]
This is likely fixed by v1.7.1.  You can set min_zoom and max_zoom either in the leaflet-map shortcode or in the settings.  Please reopen if this persists.
