### ISSUE TITLE
Missing option to adapt attribution to different tile layer

### ISSUE THREAD

**Issue by jongleur1983** [bozdoz/wp-plugin-leaflet-map#12]
Great plugin, thanks for it. Replaced another one by it and I like it basically.
Nevertheless I want to use a different tile provider than mapbox.
It's possible to adjust the tile url pattern, but the attribution stays the same and there is no way to configure it.

I fear this leads to more usages of the plugin using the maps without proper - or even with wrong - attribution.

**Comment by bozdoz** [comment]
Thanks! It's been added! I wanted to have a list of attributions, so I added support for a semi-colon separated list instead.  Didn't see your pull request until after.  Thanks again!
