### ISSUE TITLE
Incorrect marker option name for adding class to icon

### ISSUE THREAD

**Issue by mxgnr** [bozdoz/wp-plugin-leaflet-map#125]
Hi there, 

First of all, thank you for your work for this very useful plugin, it speeds up a lot leaflet integration :)

I may have found a bug in the marker shortcode attributes for adding a class to the image : it's actually set to `iconClass` in the plugin but leaflet does not add the new class, as the official documentation says to use `className` option instead (https://leafletjs.com/reference-1.7.1.html#icon-classname). 
I've tried by manually editing the marker shortcode class and it's working but only for image tags, not for svg only markers (it may need a fix, but since i'm using only images, it's not bothering me).

**Comment by bozdoz** [comment]
There is a demo of this in the Shortcode helper, so I believe it is working correctly. 

Let me know if I'm misunderstanding this.

<img width="309" alt="Screen Shot 2021-06-24 at 10 55 18 PM" src="https://user-images.githubusercontent.com/1410985/123357042-4576c680-d53f-11eb-9e6e-545a8b2fd4db.png">
