### ISSUE TITLE
JavaScript / CSS don't load on archive page

### ISSUE THREAD

**Issue by xballoy** [bozdoz/wp-plugin-leaflet-map#127]
First of all I'm not 100% sure if it's an issue with the plugin / my theme or Wordpress.

**My issue**
When I add a leaflet shortcode in my category description the JavaScript and the CSS don't load.

**Steps to reproduce:**
1. Add any leaflet shortcode into the description of your category
2. Go the the category archive page
3. The html is rendered 
```
<div class="leaflet-map WPLeafletMap" style="height:250px; width:100%;"></div>
```
but the map is not displayed and no JS / CSS is loaded

![Screen Shot 2021-03-23 at 00 51 35](https://user-images.githubusercontent.com/686305/112094593-f8ffa180-8b71-11eb-8695-492960a282e3.png)

However it works when I add it on a post.

**Comment by bozdoz** [comment]
What's a category description? Is that an excerpt?

**Comment by xballoy** [comment]
My theme uses https://developer.wordpress.org/reference/functions/category_description/ under the hood to get the description. Does it answer your question?

**Comment by bozdoz** [comment]
I'll test this out and get back to you.  Thanks

**Comment by bozdoz** [comment]
At first look, it appears I had to add `do_shortcode` to the `category_description` function; but I doubt that's your problem if you already have the HTML being rendered.  Are there any JS problems in the developer tools?

here's what's working for me:

<img width="1342" alt="image" src="https://user-images.githubusercontent.com/1410985/112183487-0f8f1280-8bdd-11eb-8ee1-33e019d414ed.png">

**Comment by xballoy** [comment]
Basically my theme is doing
```php
<?php if (!empty($content['desc'])): ?>
    <?php echo wpautop( $content['desc'] ); ?>
<?php endif; ?>
```

I didn't notice yesterday but the script is wrapped in a `p` tag
<img width="717" alt="Screen Shot 2021-03-23 at 5 01 29 PM" src="https://user-images.githubusercontent.com/686305/112217934-7c180a80-8bf9-11eb-8858-55547d6be140.png">

If I change my theme to remplace `wpautop` by `do_shortcode` the script is not wrapped anymore but I still do not download Leaflet script. I cannot see any request to get it in the network panel.

**Comment by xballoy** [comment]
Some more information:
- I didn't change the settings in the plugin
- If you want to test I added a map on this category: https://vadrouilleursetsacsados.com/category/destinations/asie/myanmar/

**Comment by bozdoz** [comment]
That helps. So for some reason the javascript is not being enqueued. I'm guessing there's a problem with the logic I added to the map shortcode class; that, or your theme is doing something funky:

https://github.com/bozdoz/wp-plugin-leaflet-map/blob/master/shortcodes/class.map-shortcode.php#L33-L43

**Comment by bozdoz** [comment]
I might just change it to use wp_script_is: https://developer.wordpress.org/reference/functions/wp_script_is/

**Comment by bozdoz** [comment]
if you're able to download v2.23.1 once it's published let me know if that works!

**Comment by MildConcussion** [comment]
@bozdoz v2.23.0 worked fine here, but v2.23.1 the tiles are all messed up. 
It's no longer in a specified width container, but it overflows everywhere and there is spacing between them. 

Looking at the commit, maybe the wp_leaflet_map is enqueued, but the stylesheet isn't enqueued as it comes after the return?

**Comment by xballoy** [comment]
🎉

<img width="1567" alt="Screen Shot 2021-03-24 at 8 54 08 AM" src="https://user-images.githubusercontent.com/686305/112313705-84665900-8c7e-11eb-8ed9-5233e6e8bd79.png">

It's working fine now, thanks a lot!

**Comment by bozdoz** [comment]
I think I see it; I think did_action is what I want: https://developer.wordpress.org/reference/functions/did_action/

**Comment by MildConcussion** [comment]
The issue I encountered is also gone in the latest (v2.23.2) version. Cheers!

**Comment by xballoy** [comment]
Not working anymore with 2.23.2 :(

**Comment by bozdoz** [comment]
v2.23.3 should be a fine compromise.  I'm not sure if anyone is even using the leaflet_map_enqueue action.  It may have been added just as an option.  I thought it should fire only once, but probably won't matter, and there are better custom ways to deal with it if it does.  Having each map enqueue the required javascript and css should solve any asynchronous problems that may be happening.

**Comment by xballoy** [comment]
v2.23.3 works for me 🚀

**Comment by MildConcussion** [comment]
v2.23.3 also works fine here 👍
