### ISSUE TITLE
relations support required

### ISSUE THREAD

**Issue by scoid** [bozdoz/wp-plugin-leaflet-map#131]
need relations support like [leaflet-map lat="52.3208" lng="9.2020" zoom="14" height="500" rel="1624183"] as in https://www.openstreetmap.org/relation/1624183#map=14/52.3208/9.2020 .
Could that be feasable?

**Comment by bozdoz** [comment]
What's a relation?  Is it the polyline that's drawn in that map?

**Comment by scoid** [comment]
yes, that polyline.

**Comment by bozdoz** [comment]
I see, I don't know anything about those "relations".  I'm not sure if it's part of their terms of use, or how to use them.  Do you have any information on this?
