### ISSUE TITLE
Embed my map generated by Folium to HTML

### ISSUE THREAD

**Issue by itsoum** [bozdoz/wp-plugin-leaflet-map#132]
Can I use this library in order to embed my map which has been generated by python lib folium (it's backed by leaflet.js) to a html?

**Comment by bozdoz** [comment]
Sorry for the late reply.  Didn't notice this issue.  I am not sure what folium is, or why it's associated with WordPress. My guess is the answer is "yes", but also "not recommended at all".  Does that answer your question?
