### ISSUE TITLE
Pulling of external image code

### ISSUE THREAD

**Issue by kirksmacdonald** [bozdoz/wp-plugin-leaflet-map#137]
Hi been do some optimization of might site.

And realised the class.image-shortcode.php pulls a random image on every load

code which is the culprit line 14

$source = empty($source) ? 'https://picsum.photos/1000/1000/' : $source;

just remove the line completely unnecessary image pull

**Comment by bozdoz** [comment]
Hi!  Are you reporting a bug?  I don't understand.

**Comment by bozdoz** [comment]
If this is still an issue, please reopen.
