### ISSUE TITLE
Tooltips wrong positioning

### ISSUE THREAD

**Issue by lithos77** [bozdoz/wp-plugin-leaflet-map#149]
In my map the position of tooltips is always wrong. Also, when zooming in and out, the distance remain from the pointer.
<img width="610" alt="Schermata 2021-11-12 alle 16 33 59" src="https://user-images.githubusercontent.com/1324152/141496609-63678153-761a-40d1-b568-25b0eed547de.png">
How to fix?

**Comment by bozdoz** [comment]
Looks to me like the markers aren't positioned correctly.  If you change the markers to use the built-in (non-custom) marker, does the tooltip appear to be in the correct spot?

**Comment by lithos77** [comment]
You're right, no problems with the default icon. Tried the iconsize param too but the x,y position of the tooltip still is wrong. Temporary returned to the default one.
