### ISSUE TITLE
Do you regard the Leaflet.markercluster plugin as generic enough to be supported?

### ISSUE THREAD

**Issue by ptandler** [bozdoz/wp-plugin-leaflet-map#150]
This [marker cluster Leaflet plugin](https://github.com/Leaflet/Leaflet.markercluster) is quite nice if you have many markers close to each other or if you want to zoom out a lot. I started working on an PR and then read your Contributing guidelines that you only might consider plugins that are "completely simplistic and globally usable". I would regard the marker cluster plugin as quite "globally usable" and hopefully also "completely simplistic". What do you think?

I actually thought of adding a `[leaflet-marker-cluster-group]` shortcode to be able to define multiple groups that will get clustered. This way, only markers defined after this chortcode will go to a cluster group. This won't interfere with any existing functionality.

Or is there maybe an existing way I did miss so far how to use this plugin?

**Comment by bozdoz** [comment]
Can definitely use whatever plugins you want.  Details in the FAQ of this repo.

**Comment by ptandler** [comment]
Well, I meant, would the marker cluster plugin something you would consider to make sense to support directly in your plugin? Then I'd think to work on a PR to include this directly in the `wp-plugin-leaflet-map`. Otherwise, I'll implement it separately.

**Comment by ptandler** [comment]
You might want to have a look at PR #151
As this is my first time to write any WP plugin code, I'd appreciate your feedback. :smiley:

**Comment by hupe13** [comment]
See https://wordpress.org/plugins/extensions-leaflet-map/
Shortcode `[cluster]`
