### ISSUE TITLE
WordPress 6.0

### ISSUE THREAD

**Issue by hupe13** [bozdoz/wp-plugin-leaflet-map#160]
Hi Bozdoz,

can you please update your readme on the WordPress plugin site:

> For each compatible plugin, you do not need to release a new version — simply update the stable version's "Tested up to" value to 6.0 in your readme file.

Thank you very much.

**Comment by bozdoz** [comment]
Thank you! Made the update which should propagate and invited you to be a contributor

**Comment by hupe13** [comment]
Okay, I will do it. But it must be changed also on the WordPress site.

**Comment by bozdoz** [comment]
Should be done! It's all automated

**Comment by bozdoz** [comment]
Go for it. I'll have to manually update the svn then. And figure out how to automate this better.

**Comment by hupe13** [comment]
I changed the readmes, I hope this is okay so.

**Comment by hupe13** [comment]
Thank you very much for 5 stars!

**Comment by bozdoz** [comment]
Works great! Thanks!
