### ISSUE TITLE
Leaflet V 1.8.0

### ISSUE THREAD

**Issue by hupe13** [bozdoz/wp-plugin-leaflet-map#162]
Hi Bozdoz,

Leaflet V 1.8.0 is released. The plugin works with this. But there are  new options:  ` integrity="sha512-...." crossorigin=""`.  You should make them available.

Thank you very much.

**Comment by bozdoz** [comment]
I'll update the leaflet version, but it occurred to me that wordpress doesn't support script attributes, and has an open ticket to support it for the past 10 years! 😱 

https://core.trac.wordpress.org/ticket/22249

**Comment by bozdoz** [comment]
resolved in [0b11062ce2c29e77f8b7f9def8011a2f240f0b87](https://github.com/bozdoz/wp-plugin-leaflet-map/commit/0b11062ce2c29e77f8b7f9def8011a2f240f0b87)
