### ISSUE TITLE
How to add a link to marker?

### ISSUE THREAD

**Issue by hexclann** [bozdoz/wp-plugin-leaflet-map#177]
The documentation says:

> ...and add a link like you normally would with the WordPress editor.

What does it mean? Is there any example shortcode?

**Comment by hupe13** [comment]
There are examples on the shortcode helper page.
`[leaflet-marker ....]<a href="https://domain.tld">Description</a>[/leaflet-marker]`

**Comment by bozdoz** [comment]
It means add a link with the Wordpress editor. Nothing to do with this plug-in
