### ISSUE TITLE
pagebuilder having problems with leaflet map plugin

### ISSUE THREAD

**Issue by YiuriV** [bozdoz/wp-plugin-leaflet-map#18]
Hi,
I am using the siteorigin wordpress pagebuilder plugin to get a nice 2 column page layout, but the plugin has some trouble with my leaflet map. I use the ‘Leaflet Map’ plugin, and the pagebuilder shows the map, but the marker doesn’t get shown. It also shows up some code under the map.

this is what I put in the rich editor:

[edsanimate animation=”fadeInRight” infinite_animation=”no” animate_on=”” ]
[leaflet-map lat=51.03349383458493 lng=3.7357431650161743 zoom=15 tileurl=http://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png subdomains=abc]
[leaflet-marker lat=51.033500581584455 lng=3.735791444778442]
[/edsanimate]

but this is how the page looks:
![error](https://cloud.githubusercontent.com/assets/6714529/12894996/95e1342c-ce9a-11e5-8479-7758cac0112f.png)

Any ideas on how to fix this? Thanks for looking in to it.

**Comment by bozdoz** [comment]
It works without the edsanimate shortcode?  Also, what happens when you remove the animate_on attribute?

**Comment by YiuriV** [comment]
I have removed the edsanimate shortcode (along with the animate_on attribute) but I still get code below the map. When I look into the google developer tools, I see 2 uncaught syntaxerrors. I'll put a link here to the page with the map: http://aquaterratest.azurewebsites.net/contact/contacteer-ons/

**Comment by bozdoz** [comment]
Is it supposed to be a draggable marker?

**Comment by bozdoz** [comment]
This is what happens when I test on my server:

http://imgur.com/a/5spwP

No problems at all with your given code.  I'm not sure where the conflict is.  If you temporarily disable a plugin, does it work?

**Comment by YiuriV** [comment]
It's supposed to be a fixed non-draggable marker, but I tried that code too and it also didn't work :p I've disabled my plugins but still no change. I didn't try all plugins (polylang, siteorigin widgets and page builder). I did try the code on a page without the use of the page builder, simply using the wordpress editor, and that did work, so the problem I guess would be with the page builder?

**Comment by YiuriV** [comment]
![error2](https://cloud.githubusercontent.com/assets/6714529/12941320/6ee5913c-cfd1-11e5-9581-d5d60d8d4199.png)
![error1](https://cloud.githubusercontent.com/assets/6714529/12941319/6ee40394-cfd1-11e5-9050-c59b39f71e10.png)
  
These are the errors I see in the chrome developer tools

**Comment by bozdoz** [comment]
Looks like it's removing quotes from shortcodes.

On Wed, Feb 10, 2016 at 3:37 AM, YiuriV <notifications@github.com> wrote:

> [image: error2]
> <https://cloud.githubusercontent.com/assets/6714529/12941320/6ee5913c-cfd1-11e5-9581-d5d60d8d4199.png>
> [image: error1]
> <https://cloud.githubusercontent.com/assets/6714529/12941319/6ee40394-cfd1-11e5-9050-c59b39f71e10.png>
>
> These are the errors I see in the chrome developer tools
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/bozdoz/wp-plugin-leaflet-map/issues/18#issuecomment-182238413>
> .
>



-- 
Benjamin J DeLong
@bozdoz <https://twitter.com/bozdoz>
902-877-2117

**Comment by bozdoz** [comment]
This has been fixed in the current version.  Please update and "Close and comment" if this has been resolved.

**Comment by YiuriV** [comment]
Indeed it works now, Thanks!
