### ISSUE TITLE
layerswitch on leaflet-geojson polygons

### ISSUE THREAD

**Issue by RayHollister** [bozdoz/wp-plugin-leaflet-map#183]
I am trying to add a layerswitch to toggle a polygon laye on and off, but I can't seem to figure out how to make it work. I have Leaflet Map and Extensions for Leaflet Map both installed. Here's my shortcode:

[leaflet-map fitbounds height=1000 detect-retina zoomcontrol scrollwheel tileurl=https://{s}.basemaps.cartocdn.com/light_all/{z}/{x}/{y}{r}.png attribution='&copy; <a href="https://www.openstreetmap.org/copyright">OpenStreetMap</a> contributors &copy; <a href="https://carto.com/attributions">CARTO</a>.' zoom=16]

[leaflet-geojson src=https://raw.githubusercontent.com/RayHollister/JacksonvilleNeighborhoods/main/neighborhoods.geojson]<strong>{NAME}</strong>[/leaflet-geojson]
[layerswitch]
[markerClusterGroup feat="name" strings="neighborhoods" groups="Neighborhoods"]
[fullscreen]
[zoomhomemap fit]

**Comment by hupe13** [comment]
`[markerClusterGroup feat="name" strings="neighborhoods" groups="Neighborhoods"]`
is only for markers, inluding geojson markers. Switching other geojson on and off isn't possible (yet) and needs extra programming.
You can take a look at [`[hover]`](https://leafext.de/en/hover/hover/).

**Comment by RayHollister** [comment]
Darn. I thought that might be the case. Thanks for that clarification. 

I'll work on integrating this plugin (https://github.com/ptma/Leaflet.Legend) into my Wordpress plugin, assuming you don't want to add it to Extensions for Leaflet Map.

**Comment by hupe13** [comment]
I think this function might also interest others. If you want to help me, feel free to do so.
