### ISSUE TITLE
zoom validation

### ISSUE THREAD

**Issue by hupe13** [bozdoz/wp-plugin-leaflet-map#189]
https://github.com/bozdoz/wp-plugin-leaflet-map/blob/fa440060e7b9a0b77dc160a8adc201801502e77c/shortcodes/class.map-shortcode.php#L215
should be
` 'zoom' => FILTER_VALIDATE_INT, `

here also:
https://github.com/bozdoz/wp-plugin-leaflet-map/blob/fa440060e7b9a0b77dc160a8adc201801502e77c/shortcodes/class.map-shortcode.php#L159

Should I change this?

**Comment by bozdoz** [comment]
why INT?

**Comment by hupe13** [comment]
Today I answered a [support question](https://wordpress.org/support/topic/marker-not-visible-on-southern-hemisphere/). Apologies for communicating in german, we then switched to mail. The problem was, some markers were displayed, others not. The reason was, the user has defined a floating point number for min_zoom: "2.3". Then he defined "2" and it worked.
I was able to reproduce the error.

I read the [documentation](https://leafletjs.com/examples/zoom-levels/) about zoom again. Floating point numbers only occur when fractional zoom is used. Such an option does not exist in Leaflet Map.

Valid values for min_zoom, max_zoom and zoom are integers from 0 to 20. max_zoom depends on the used tiles.

**Comment by bozdoz** [comment]
I think I understand. Zoom can be fractional, min and max can only be ints. Is that true?

**Comment by hupe13** [comment]
Yes, min and max should be ints.
From the [documentation](https://leafletjs.com/examples/zoom-levels/):

> Fractional zoom is disabled by default. To enable it, use the [map’s zoomSnap option](https://leafletjs.com/reference.html#map-zoomsnap).

This is not used in Leaflet Map, therefore values for zoom should be int.
