### ISSUE TITLE
Tiles are returning 410 gone errors

### ISSUE THREAD

**Issue by dovidev** [bozdoz/wp-plugin-leaflet-map#191]
Using the Map Tile URL of https://api.tiles.mapbox.com/v4/mapbox.light/{z}/{x}/{y}.png?access_token=REDACTED, I get errors that look like this:

`GET https://api.tiles.mapbox.com/v4/mapbox.light/4/6/5.png?access_token=REDACTED 410 (Gone)`

I saw some things that said to use this URL instead:
https://api.mapbox.com/styles/v1/{id}/tiles/{z}/{x}/{y}?access_token=REDACTED

However, when I tried that, I get

`Error: No value provided for variable {id}`

**Comment by bozdoz** [comment]
Should those urls work?

**Comment by dovidev** [comment]
> Should those urls work?

Yes, they should work. Obviously, my access token has been redacted so the links here won't work. This worked great until recently when it just stopped working.

**Comment by dovidev** [comment]
> [bozdoz](https://github.com/bozdoz) added the [needs more info]
What more info do you need?

**Comment by hupe13** [comment]
Maybe you can get info [here](https://github.com/leaflet-extras/leaflet-providers#mapbox).
https://raw.githubusercontent.com/leaflet-extras/leaflet-providers/master/leaflet-providers.js

**Comment by bozdoz** [comment]
When I try your URL, I get:

> Classic styles are no longer supported; see https://blog.mapbox.com/deprecating-studio-classic-styles-d8892ac38cb4 for more information

This is irrelevant to this plugin.

**Comment by dovidev** [comment]
I'm seeing that Mapbox has changed some things. What I'm not seeing is what I need to put in this leaflet field to make the plugin work.

**Comment by bozdoz** [comment]
<img width="714" alt="Screen Shot 2022-12-22 at 1 27 22 PM" src="https://user-images.githubusercontent.com/1410985/209191923-e102fbfa-112a-4342-b4e0-b34d7bf19464.png">

I'm not sure what mapbox needs now.  I haven't looked into it.  I suspect the answer is in that link: https://blog.mapbox.com/deprecating-studio-classic-styles-d8892ac38cb4

**Comment by bozdoz** [comment]
My guess is they want you to create a new map (which gives you the {id} you may or may not be looking for): basically style your own map under your own account, and use that

**Comment by dovidev** [comment]
I'm confused. Where would I create a map? I'm using Leaflet Map Version 3.0.5 which has a series of shortcodes to use. Here's what my code looks like.

```
[leaflet-map height=450 lat=37.8 lng=-92.5 zoom=4 min_zoom=3 max_zoom=15 doubleClickZoom zoomcontrol !scrollwheel]	 	 
[leaflet-geojson src="https://aquissolutions.com/wp-content/themes/astra-child/coverage-map.json.php"]{name}[/leaflet-geojson]
```

**Comment by bozdoz** [comment]
It's in the README:

[leaflet-map tileurl="https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png"]

here: https://github.com/bozdoz/wp-plugin-leaflet-map/blob/master/README.md?plain=1#L134

And in the example page: 

https://github.com/bozdoz/wp-plugin-leaflet-map/blob/master/templates/shortcode-helper.php#L75

**Comment by bozdoz** [comment]
Please re-open if you believe this issue is still relevant

**Comment by dovidev** [comment]
That got the map to show but it doesn't read in my .json for regions as it did before. What do I need to do to make that work.

```
<div id="coverage-map">	 	 
[leaflet-map height=450 lat=37.8 lng=-92.5 zoom=4 min_zoom=3 max_zoom=15 doubleClickZoom zoomcontrol !scrollwheel]	 	 
[leaflet-geojson src="https://aquissolutions.com/wp-content/themes/astra-child/coverage-map.json.php"]{name}[/leaflet-geojson]	 	 
</div>
[coverage_map_jquery]

```

**Comment by dovidev** [comment]
I've updated my last comment to include the actual javascript reference. Including that Javascript or not does not change that the json for regions overlayed on the may doesn't work. I'm just trying to figure out how to use this plugin now that something has changed. As far as I can tell, I'm using the most up-to-date version of the plugin. The page is here: https://aquissolutions.com/coverage/.  How should this be done?

**Comment by dovidev** [comment]
Got it figured out. It looks like it was also throwing an invalid json error. The JSON itself was valid but one of the features didn't have the geometry type set. In looking at the code there, it would be really easy to change that error message to actually say that's what's going on instead of saying the JSON was invalid.
