### ISSUE TITLE
Questions about Pull Request

### ISSUE THREAD

**Issue by hupe13** [bozdoz/wp-plugin-leaflet-map#193]
Hi Bozdoz,

I have fixed some [things ](https://github.com/bozdoz/wp-plugin-leaflet-map/compare/master...hupe13:wp-plugin-leaflet-map:master)or tried to. Can you please check if everything is correct? You had written at some point that everything is automated. I don't want to make a mistake.
I also tried to fix #182 , but I didn't understand what was going on with the $raw_map_options.

Thank you very much.

**Comment by bozdoz** [comment]
Opened #195.  Looks good to me.  Good to merge?
