### ISSUE TITLE
publish new version

### ISSUE THREAD

**Issue by bozdoz** [bozdoz/wp-plugin-leaflet-map#196]

**Comment by hupe13** [comment]
If you publish a new version, change this:
https://github.com/bozdoz/wp-plugin-leaflet-map/blob/858ca5ac24be065e4d9c525690112ebb8f6741b0/class.leaflet-map.php#L25
```php
    public static $leaflet_version = '1.9.3';
```
Or will I interfere with your flow if I change it?

**Comment by bozdoz** [comment]
I can do that
