### ISSUE TITLE
Map is not shown

### ISSUE THREAD

**Issue by Mannshoch** [bozdoz/wp-plugin-leaflet-map#20]
If I setup Markers I'm not able to see anything.
Firebug give me following errors.

```
ReferenceError: WPLeafletMapPlugin is not defined
	

WPLeafletMapPlugin.add(function () {

	
/impressum/ (Zeile 147, Spalte 13)
ReferenceError: WPLeafletMapPlugin is not defined
	

WPLeafletMapPlugin.add(function () {

	
/impressum/ (Zeile 167, Spalte 13)
TypeError: a is undefined
	

...,f).emulateTransitionEnd(150):f()};var d=a.fn.alert;a.fn.alert=function(b){retur...

	
autopti...4260.js (Zeile 11, Spalte 562)
```

**Comment by bozdoz** [comment]
Not able to reproduce this. See screenshots:

![screenshot from 2016-06-29 16 51 23](https://cloud.githubusercontent.com/assets/1410985/16466548/efa24c8c-3e19-11e6-944a-fdfb65906bce.png)

![screenshot from 2016-06-29 16 51 36](https://cloud.githubusercontent.com/assets/1410985/16466555/f2f751c0-3e19-11e6-93d5-d3e6150d4cb3.png)

**Comment by bozdoz** [comment]
Also note: this is a fresh install of WordPress with the latest plugin.  Perhaps you are not using Wordpress?

**Comment by Mannshoch** [comment]
I Use Wordpress 4.5.3 with Leaflet Map 1.16
Didn't changed any settings in Leaflet.

As a test I copied the short tags form the examples in Backend to a Site. (the shortcodes work in Backend)

**Comment by bozdoz** [comment]
Tested again on Firefox.  My best guess is that there's a conflict with another plugin?  Perhaps you could try deactivating plugins temporarily to see if that solves it.  Otherwise, it's possible that the theme you're using has removed the `<?php wp_head(); ?>` from the header.php.  In that case, the javascript file that defines `WPLeafletMapPlugin` wouldn't have loaded.

**Comment by Mannshoch** [comment]
Correct. The following app was evil one:
https://wordpress.org/plugins/autoptimize/

**Comment by bozdoz** [comment]
ah, perhaps that plugin renamed the `WPLeafletMapPlugin` variable, or moved it to the footer instead.  In Firebug I think you should be able to figure out if it was loaded at all by typing the variable name to see if it exists in the window scope.  Glad it's resolved either way.
