### ISSUE TITLE
set automatic the actual leaflet version on update

### ISSUE THREAD

**Issue by hupe13** [bozdoz/wp-plugin-leaflet-map#202]
It's a suggestion: If someone uses the default setting for javascript url and css url, it will be checked and updated if necessary on plugin updates.

**Comment by bozdoz** [comment]
Do you mean, update the db value if it was saved under an older version?

Maybe we could add a checkbox for "Use latest from CDN", and if that's checked, we always get the static, updated version.  Maybe there's a "latest" url too

**Comment by bozdoz** [comment]
Yeah, looks like default could be:
https://unpkg.com/leaflet@latest/dist/leaflet.js
and 
https://unpkg.com/leaflet@latest/dist/leaflet.css

**Comment by hupe13** [comment]
>  it will be checked

I mean, verify that the latest version is being used

> checkbox for "Use latest from CDN",

This idea is good. This could also be done when there is no plugin update.

> @latest

That wouldn't be so good for SEO to put that in the db. @latest is a redirect to the current version. The redirect url (e.g. @1.9.3) should be put into the db.

**Comment by bozdoz** [comment]
How is latest bad for SEO?

**Comment by hupe13** [comment]
I read the documentation about SEO and 302 redirects again, it is not bad.

**Comment by hupe13** [comment]
Hi Bozdoz,
I have been working with this setup for a while now and have received repeated errors from unpkg.com. When I use a concrete version, there are never problems.

**Comment by bozdoz** [comment]
OK, so we can have a banner on the admin page that states whether they're up to date with latest in defaults
