### ISSUE TITLE
Allow images in add_popup_to_shape

### ISSUE THREAD

**Issue by bozdoz** [bozdoz/wp-plugin-leaflet-map#204]
related to #185

**Comment by bozdoz** [comment]
This may already be possible

**Comment by hupe13** [comment]
This has always been [possible](https://leafext.de/en/cluster/placementstrategies/). If, then the editor that changes the code annoys me. But I am currently testing a [solution](https://github.com/hupe13/extensions-leaflet-map-github/blob/da0a849adab63d9459e448d1213a7e8c13b64a56/php/enqueue-leafletplugins.php#L208-L217).
