### ISSUE TITLE
Boxes around marker icon and shadow

### ISSUE THREAD

**Issue by Jmuccigr** [bozdoz/wp-plugin-leaflet-map#21]
I'm not seeing the icon shadows for my markers. Instead I get just the outline of a box for the image. WP 4.6.1

**Comment by bozdoz** [comment]
Depends on where you're hosting your leaflet js file

**Comment by Jmuccigr** [comment]
I'm just using the default settings.

**Comment by bozdoz** [comment]
Fresh install, I can't reproduce this.  I need some more info to be of any more help.

Here's an example post with [leaflet-map] and [leaflet-marker]:

![screenshot from 2016-10-20 20-18-59](https://cloud.githubusercontent.com/assets/1410985/19581346/ac8b799a-9702-11e6-9562-ee878e441061.png)

**Comment by Jmuccigr** [comment]
Nope, not for me, with neither a new page or a new post. See screenshot (where the map height is 500, but that doesn't change anything). Text of the page/post is simply `[leaflet-map] [leaflet-marker]`. You can see that there are two boxes, actually: one around the marker and the other around the shadow, which actually **is** there (so I'm changing the title of this issue).

I'm using reclaim hosting. Are there more details that would help?
![unspecified](https://cloud.githubusercontent.com/assets/615115/19581864/4e27538c-96fe-11e6-9bbe-4281b07c7087.png)

**Comment by bozdoz** [comment]
There are boxes around all of the tile images too.  Maybe open the developer window on your browser?  Maybe you've enabled some experimental "border around every image" feature?

**Comment by Jmuccigr** [comment]
Ah, I thought those were lat/long lines.

But, no, if I switch browsers, it's the same. I'll send you the URL.

**Comment by Jmuccigr** [comment]
For posterity, @bozdoz found a line in the theme's css (fkidd) which uses box-shadow. I was able to work around it by modifying the css to have no shadows around the relevant elements.
