### ISSUE TITLE
maxZoom > 18

### ISSUE THREAD

**Issue by hupe13** [bozdoz/wp-plugin-leaflet-map#215]
see [support forum](https://wordpress.org/support/topic/map-is-empty-when-markers-nearby-each-other/#post-16506106)

It is a bug.
I added maxZoom to tile layers options and I get zoom > 18.

https://github.com/bozdoz/wp-plugin-leaflet-map/blob/39019ce82a5227915adb556b61035232a65f3a5a/shortcodes/class.map-shortcode.php#L199-L200

```php
            'noWrap' => filter_var(empty($nowrap) ? $settings->get('tile_no_wrap') : $nowrap, FILTER_VALIDATE_BOOLEAN),
            'maxZoom' => $atts['maxZoom']
        );
```

`maxZoom: 18`  comes from:

https://github.com/Leaflet/Leaflet/blob/18d703176bec040a06f233702d3eec141e95daaf/src/layer/tile/TileLayer.js#L46-L48

**Comment by bozdoz** [comment]
Could you give me a shortcode to test this with?

**Comment by hupe13** [comment]
https://leafext.de/debug/
openstreetmap.fr has a maxzoom of 20.
Please open the developer console. I loaded a changed leaflet-src.js with debug messages in console.log.

**Comment by bozdoz** [comment]
[leaflet-map height=200px width=100% max_zoom=23 !detect-retina zoomcontrol tileurl=https://{s}.tile.openstreetmap.fr/osmfr/{z}/{x}/{y}.png subdomains=abc]
