### ISSUE TITLE
marker title and php filter

### ISSUE THREAD

**Issue by hupe13** [bozdoz/wp-plugin-leaflet-map#220]
Hi Bozdoz,

someone uses german umlauts like `"ü"` in `[marker title="Mühle"  ....]`.
If the filter is [FILTER_SANITIZE_FULL_SPECIAL_CHARS](https://github.com/bozdoz/wp-plugin-leaflet-map/blob/b7fb694f6695e1b5f2b1df8ee17abd0bf40bb082/shortcodes/class.marker-shortcode.php#L89), then the result is `"M&uuml;hle"`, if the filter is FILTER_SANITIZE_SPECIAL_CHARS the result is `"Mühle"`. Is it a problem to change the filter to FILTER_SANITIZE_SPECIAL_CHARS?

Thank you very much.

**Comment by bozdoz** [comment]
Sounds like it's a fair idea. You want to submit a pr?

**Comment by bozdoz** [comment]
I'd have to look up the difference. We mostly want to avoid injecting javascript or html.

**Comment by bozdoz** [comment]
Don't think I'm using JavaScripts unescape

**Comment by hupe13** [comment]
I'm sorry, I have misunderstood something, I just see you have your own unescape:
https://github.com/bozdoz/wp-plugin-leaflet-map/blob/b7fb694f6695e1b5f2b1df8ee17abd0bf40bb082/scripts/construct-leaflet-map.js#L225
Right?

**Comment by bozdoz** [comment]
Yep, looks right
