### ISSUE TITLE
Height setting does not accept percentage values

### ISSUE THREAD

**Issue by sm8ps** [bozdoz/wp-plugin-leaflet-map#225]
Specifying height="50%" results in a non-visible map, regardless if in the short-code itself or in the general settings. I have seen #144 but that does not clarify things to me.

**Comment by bozdoz** [comment]
This is a css problem. 50% is ambiguous. The question is "50% of what?". Maybe try "50vh" which is 50% of the viewport height. Otherwise you could do a search for "how to set something to 50% height in css"

**Comment by sm8ps** [comment]
Many thanks for this explanation and the concise answer, @bozdoz! I hope others may find it as helpful as I did.
