### ISSUE TITLE
Doubts about creating a new map

### ISSUE THREAD

**Issue by IggyAl** [bozdoz/wp-plugin-leaflet-map#230]
Hello,

I have created a map with some markers (with custom icons), by using Leaflet: https://imgur.com/Uv7u6zV

I would like to know if it is easy to add Geocoding (search by postal code) and Satellite view, using the plugin, I have to program or how I could do it.

Thank you.

**Comment by hupe13** [comment]
Crosspost https://wordpress.org/support/topic/doubts-about-creating-a-new-map/
