### ISSUE TITLE
Blank at default zoom

### ISSUE THREAD

**Issue by nizarfadlan** [bozdoz/wp-plugin-leaflet-map#242]
Can anyone help with the code on the shortcode just
```
[leaflet-map]
[leaflet-marker visible]
<a>Link</a>
[/leaftlet-marker]
```

Here using default zoom 7, min zoom 1, max zoom 10, fitbounds.
https://github.com/bozdoz/wp-plugin-leaflet-map/assets/40895148/81366ecc-24b4-4a46-98e2-4ae5362f340d

**Comment by hupe13** [comment]
One marker does not have bounds, you need to specify lat, lng and zoom.
```
[leaflet-map lat=...  lng=...  zoom=...]
[leaflet-marker visible]
<a>Link</a>
[/leaftlet-marker]
```
