### ISSUE TITLE
The Plugin is not php 8.2 compatible

### ISSUE THREAD

**Issue by BackuPs** [bozdoz/wp-plugin-leaflet-map#243]
If you turn on debug mode in php 8.2  you get about 30 warning messages

Deprecated: Creation of dynamic property Leaflet_Map_Plugin_Option::$display_name is deprecated in /var/docs/wpreview.tst/public/wp-content/plugins/leaflet-map/class.plugin-option.php on line 85
Deprecated: Creation of dynamic property Leaflet_Map_Plugin_Option::$min is deprecated in /var/docs/wpreview.tst/public/wp-content/plugins/leaflet-map/class.plugin-option.php on line 85
Deprecated: Creation of dynamic property Leaflet_Map_Plugin_Option::$max is deprecated in /var/docs/wpreview.tst/public/wp-content/plugins/leaflet-map/class.plugin-option.php on line 85
Deprecated: Creation of dynamic property Leaflet_Map_Plugin_Option::$step is deprecated in /var/docs/wpreview.tst/public/wp-content/plugins/leaflet-map/class.plugin-option.php on line 85
Deprecated: Creation of dynamic property Leaflet_Map_Plugin_Option::$min is deprecated in /var/docs/wpreview.tst/public/wp-content/plugins/leaflet-map/class.plugin-option.php on line 85
Deprecated: Creation of dynamic property Leaflet_Map_Plugin_Option::$max is deprecated in /var/docs/wpreview.tst/public/wp-content/plugins/leaflet-map/class.plugin-option.php on line 85
Deprecated: Creation of dynamic property Leaflet_Map_Plugin_Option::$step is deprecated in /var/docs/wpreview.tst/public/wp-content/plugins/leaflet-map/class.plugin-option.php on line 85

Warning: Array to string conversion in /var/docs/wpreview.tst/public/wp-content/plugins/leaflet-map/class.plugin-option.php on line 85

Warning: Undefined property: Leaflet_Map_Plugin_Option::$min in /var/docs/wpreview.tst/public/wp-content/plugins/leaflet-map/class.plugin-option.php on line 85

etc etc etc

Please declare the variables within the class.

	
	public $display_name='';
	public $min='';
	public $max='';
	public $step='';

Thank you

**Comment by bozdoz** [comment]
Thank you!
