### ISSUE TITLE
Map Marker Displays Correctly While Logged Into Wordpress But Not for Logged Out Visitors

### ISSUE THREAD

**Issue by Escondido** [bozdoz/wp-plugin-leaflet-map#245]
I'm not sure when the issue cropped up, but I just noticed the map marker shows up correctly as a blue icon when I'm logged in. However, logged out it doesn't show up with any browser.  All I see is a broken image and "mark" or "marker" depending on the browser (see attached)

I'm using the following
- Cloudpanel with Varnish Cache
- Cloudflare Free
- Elementor Pro
- Voxel Theme
- Perfmatters
- Bunch of other plugins

I tried deactivating all plugins and that didn't resolve the issue.  Cleared all cache with the same outcome. It doesn't make sense it only shows up while logged into the website. I know it used to show up fine, I just can't pinpoint the problem. 

Using Voxel tags the shortcode is as follows; 

[leaflet-map lat=@post(location.lat) lng=@post(location.lng) zoom=14 zoomcontrol=1]
[leaflet-marker lat=@post(location.lat) lng=@post(location.lng)]

It automatically pulls in the coordinates and shows the location. 

Any suggestions on how to fix it?  Thanks. 

![listing](https://github.com/bozdoz/wp-plugin-leaflet-map/assets/9452405/a1e9487f-a072-441f-96de-438a87dc0b56)

**Comment by hupe13** [comment]
Open the developer console of your browser and search any errors.
Do you have an URL to a test page?

**Comment by Escondido** [comment]
I see two errors showing a 404 error code about the marker-icon and marker-shadow. 

https://www.catchadoc.com/doctors/dr-john-vierlingmd/

**Comment by hupe13** [comment]
I can't acces the URL, I am being blocked (403 error).

**Comment by Escondido** [comment]
I have a lot of people trying to hack my website, so Cloudflare is blocking all traffic outside USA.  What country is your ip address located and I'll whitelist it.

**Comment by Escondido** [comment]
Should work now.

**Comment by hupe13** [comment]
I guess either Elementor or a caching plugin is the reason. Try to use iconurl and the other options. You can use e.g. marker from https://github.com/pointhi/leaflet-color-markers, [examples](https://leafext.de/grouping/markers/). Or use [ExtraMarker](https://leafext.de/en/doku/extramarker/) from [Extensions for Leaflet Map](https://wordpress.org/plugins/extensions-leaflet-map/).

**Comment by Escondido** [comment]
I got it working now using the other plugin.  Finally got my pagespeed score up to 100 by getting rid of Google maps, so I'm happy.  Putting the code down below in case anybody else needs encounters the same problem. 

[leaflet-map lat=@post(location.lat) lng=@post(location.lng) height=400px zoom=13 zoomcontrol=1]
[leaflet-extramarker markerColor=orange-dark shape=circle
lat=@post(location.lat) lng=@post(location.lng)]
