### ISSUE TITLE
Shortcode helper example Alternate Map Tiles w/scrollwheel

### ISSUE THREAD

**Issue by hupe13** [bozdoz/wp-plugin-leaflet-map#246]
Hi Bozdoz,

you should change the example "Alternate Map Tiles w/scrollwheel", `https://stamen-tiles-{s}.a.ssl.fastly.net/watercolor/{z}/{x}/{y}.jpg subdomains=a,b,c,d ` is not valid any more.

Thank you very much.

**Comment by bozdoz** [comment]
Thank you!
