### ISSUE TITLE
php 8.2 compatibility

### ISSUE THREAD

**Issue by hupe13** [bozdoz/wp-plugin-leaflet-map#247]
Hi Bozdoz,

please see https://wordpress.org/support/topic/plugin-is-not-php-8-2-compatible-2/#post-17457554.

I have not any experience in programming `class`. So I found a solution via Google. I wrote in file class.plugin-option.php line 21:
`#[AllowDynamicProperties]`
With this change I don't get any warnings with php 8.2.

**Comment by bozdoz** [comment]
Looks like it's already fixed but maybe the publish script has failed:

https://github.com/bozdoz/wp-plugin-leaflet-map/commit/c3a3b02494c0a8582896ac36ad5ef406ed739db5

**Comment by hupe13** [comment]
Yes, I tested it again with the Github version, it works. Yesterday I tested it with the WordPress version. I have seen the [change](https://github.com/bozdoz/wp-plugin-leaflet-map/commit/c3a3b02494c0a8582896ac36ad5ef406ed739db5) but not compared it.

**Comment by bozdoz** [comment]
Yeah I'll have to check why the publish build failed

**Comment by bozdoz** [comment]
Oh actually looks like I just need a new version 
![image](https://github.com/bozdoz/wp-plugin-leaflet-map/assets/1410985/3b420b64-4c8d-4747-8362-ff21364091cf)
I can look into doing that asap. Maybe tomorrow

**Comment by hupe13** [comment]
Thank you very much, works with php 8.3 also.
