### ISSUE TITLE
circle and polygons are not showing any more

### ISSUE THREAD

**Issue by omarllorens** [bozdoz/wp-plugin-leaflet-map#255]
Hi everyone and thank you for your help in advance.

I want to say that is my first time that I used this plugin and maybe I need mor know how.

I was using the next short code in my wordpress without any problem during some time, but now leaflet-circle is not showing.

[leaflet-map lat=38.636778 lng=-0.002111 zoom=13 zoomcontrol !show_scale] [leaflet-circle lat=38.636778 lng=-0.002111 radius=1000] [leaflet-scale position=topright]

I've tried other examples with polygons but not showing too. The makers yes.

You can check here: https://costahousesluxuryvillas.com/propiedad/exclusiva-finca-con-mas-de-40-000m2-de-parcela-frente-el-portichol-javea/?_post_id=300502

Is possible that we have a problem with some extra css that hide the circle?

Thank you.

**Comment by hupe13** [comment]
It seems you have typos? You are using in your map
```
lat = 38.754195415742 lng = 0.2173086227139
```
lat and lng in your code above are other ones.

**Comment by omarllorens** [comment]
Sorry I've pasted a different example. But the error is the same, I have the same problem in all properties that have a map.

Now yes.
[leaflet-map lat=38.754195415742 lng=0.2173086227139 zoom=13 zoomcontrol !show_scale] 
[leaflet-circle lat=38.754195415742 lng=0.2173086227139 radius=1000] 
[leaflet-scale position=topright]

You can check here: https://costahousesluxuryvillas.com/propiedad/exclusiva-finca-con-mas-de-40-000m2-de-parcela-frente-el-portichol-javea/?_post_id=300502

**Comment by hupe13** [comment]
It works in my test installation with Elementor and the theme GeneratePress I'm using on my websites too. So the reason may be a caching plugin or any other plugin. Try to disable the cache.

**Comment by omarllorens** [comment]
Thank you. I've check in other installation and works too. 

I'm going to try to do that you say.

Thank you again.
