### ISSUE TITLE
WP 6.6

### ISSUE THREAD

**Issue by hupe13** [bozdoz/wp-plugin-leaflet-map#257]
Hello Bozdoz,

I changed "Tested up to: 6.4.2" to "Tested up to: 6.6". It will be pushed to the readme.txt in the WordPress repository?  Is this right?

**Comment by bozdoz** [comment]
Yep that sounds right

**Comment by hupe13** [comment]
But why it doesn't changed this [here](https://wordpress.org/plugins/leaflet-map/)?

**Comment by bozdoz** [comment]
Hmm not sure. I'll take a look tonight

**Comment by bozdoz** [comment]
I can't figure out how to get the github workflow to work for the update-workflow file. I added a manual trigger, and just triggered it from here: 

https://github.com/bozdoz/wp-plugin-leaflet-map/actions/workflows/update-workflow.yml

**Comment by bozdoz** [comment]
Still not sure why it's not working; I had to reset a password, but also I couldn't manually run the script; I had to manually login instead

**Comment by hupe13** [comment]
> I had to reset a password

Did you receive this [mail](https://make.wordpress.org/plugins/2024/06/29/password-reset-required-for-plugin-authors/)?

**Comment by bozdoz** [comment]
I did, yes

**Comment by hupe13** [comment]
Unfortunately I can't help you with the workflow. But I close this issue, "Tested up to" shows the right version. Thank you very much.
