### ISSUE TITLE
geojson icons

### ISSUE THREAD

**Issue by hupe13** [bozdoz/wp-plugin-leaflet-map#259]
Hi Bozdoz,

can you provide an option to pick up the icon from geojson properties? Someone asked in the [forum](https://wordpress.org/support/topic/geojson-i-need-to-use-this-i-have-100s-of-markers-causing-load-probs/).

Thank you very much.

**Comment by hupe13** [comment]
I made an [example](https://leafext.de/extra/geojson-icon/) with extra code. I didn't see, that you labeled this with priority. It is of course better if it is in the `leaflet-geojson` shortcode.

**Comment by bozdoz** [comment]
Took a look.  I don't think I'm going to add this.  Maybe someone else could come up with a workable solution; I'm not sure.  But just looking over how much work it is just to get custom icons in geojson seems like it's not worth adding.  I'm glad it's still possible with a workaround like you provided, but for the vast majority of people, I can't imagine it would be worth having.

**Comment by hupe13** [comment]
Okay. Thank you very much.
