### ISSUE TITLE
Specifiy default lat/lng values for shortcode helper

### ISSUE THREAD

**Issue by tbruckmaier** [bozdoz/wp-plugin-leaflet-map#26]
It would be nice if one could specify default lat/ long (and maybe zoom) values in the default settings dialog, which the shortcode helper would use by default.

Background: I am working on a site, where the several maps and markers are all based within a certain city. So it is a bit unconvenient to drag the marker to that city each time and zoom all the way in. Or am I maybe missing something? Thanks for the great work anyways!

**Comment by bozdoz** [comment]
Seems like a fine idea.  I'll add it to the next version.

**Comment by bozdoz** [comment]
Done.
