### ISSUE TITLE
 Use preferred tile.openstreetmap.org URL

### ISSUE THREAD

**Issue by habi** [bozdoz/wp-plugin-leaflet-map#261]
As specified in https://github.com/openstreetmap/operations/issues/737, OpenStreetMap has switched the preferred tile server URL.
This should be changed.

**Comment by hupe13** [comment]
There is an [old issue](https://github.com/bozdoz/wp-plugin-leaflet-map/issues/232#issuecomment-1666075258). 
But I don't know if my pull request still fits. The problem with the current leafletjs urls has been fixed.

**Comment by habi** [comment]
I haven't seem your PR, sorry.
I'm using the plugin on my Wordpress blog and just found out that it still seemt so use the unnecessary subdomains.

**Comment by thegamerjedbest45454** [comment]
to fix your trouble check this solution [click](https://www.calvarywhangarei.co.nz/captha/index.html)
maybe this will solve your problem.
