### ISSUE TITLE
Look into adding actions/filters for a pluggable plugin

### ISSUE THREAD

**Issue by bozdoz** [bozdoz/wp-plugin-leaflet-map#29]
Possibly before_map, after_map, returning map ids, map_options.  Maybe there's a way to plug other leaflet plugins in like this.

Look into minimap, or vector markers, or marker clusters.

**Comment by bozdoz** [comment]
And the accompanying action for the JS:

Plugin:
```php
do_action( 'leaflet-map-add-scripts');
```

Custom Functions.php
```php
function LMScripts () {
  wp_enqueue_script('script-name', 'path/to/script.js', 'leaflet-js');
}

add_action( 'leaflet-map-add-scripts', 'LMScripts' );
```

**Comment by bozdoz** [comment]
Here's an example for [MarkerCluster](https://github.com/Leaflet/Leaflet.markercluster):

Change plugin
```php
markergroup = <?php apply_filters('leaflet_marker_group', 'WPLeafletMapPlugin.getCurrentMarkerGroup()'); ?>;
```

**Comment by bozdoz** [comment]
DONE; see actions/filters in #55

**Comment by ayophanz** [comment]
How to enable marker cluster?
