### ISSUE TITLE
Leflet not loading

### ISSUE THREAD

**Issue by scubbx** [bozdoz/wp-plugin-leaflet-map#35]
Since the newest Version (2.8.3) (or maybe even sooner?) Leaflet maps included into WordPress (v 4.8.1) pages do not show up anymore. The content of the sites were not changed in any way.

Looking at the Browser debugging tools, it seems like the library is not allowed to load anymore:

![lefleterror](https://user-images.githubusercontent.com/1347421/29241137-e841e82a-7f73-11e7-896d-63ff57a502f7.png)

This happens in Firefox as well as in Chromium. It was working before in both browsers?

**Comment by bozdoz** [comment]
Both the css and js links appear valid to me:

https://unpkg.com/leaflet@1.0.3/dist/leaflet.css
https://unpkg.com/leaflet@1.0.3/dist/leaflet.js

I would think this would be a temporary issue with the cdn, and not the plugin.  Visit the links yourself to see the output, and refresh a page on your site to see if it loads properly.

**Comment by bozdoz** [comment]
Fixed the issue. Thanks!
