### ISSUE TITLE
multiple raster layers option?

### ISSUE THREAD

**Issue by lukaszkruk** [bozdoz/wp-plugin-leaflet-map#38]
@bozdoz The plugin defaults to basic OSM layer if no tileurl is specified. If tileurl is specified, the custom tile layer replaces the basic OSM layer. Is it possible to have both basic OSM layer as well as the custom one superimposed, ideally with a layer switcher tickbox? leaflet itself allows http://leafletjs.com/examples/layers-control/ - can this be achieved with this plugin?

**Comment by bozdoz** [comment]
Not yet.

**Comment by bozdoz** [comment]
Moved to #43
