### ISSUE TITLE
add leaflet plugin to wp-plugin-leaflet-map

### ISSUE THREAD

**Issue by valeriodeluca** [bozdoz/wp-plugin-leaflet-map#39]
Hi boz! Great job!
Can I add leaflet plugin (http://leafletjs.com/plugins.html) to wp-plugin-leaflet-map code?
Tks!
Best
Valerio

**Comment by valeriodeluca** [comment]
Hi Bozdoz, I'd like add other leaflet plugins to wp-plugin-leaflet-map... sure writing code by myself. I'd like have leaflet plugins like these maps in my website:
http://www.mainjoin.eu/map/swiss/
http://www.mainjoin.eu/map/pisa/
http://www.mainjoin.eu/map/lamone/
http://www.mainjoin.eu/map/bm/
Tks :)

**Comment by valeriodeluca** [comment]
I saw that it's possible load more geojson. Can I have a layer control with checkbox button for turn on/off each geojson (layer)?
http://leafletjs.com/examples/layers-control/
Tks!
Have nice we
Valerio

**Comment by bozdoz** [comment]
re: last question

moving that issue to #43

**Comment by bozdoz** [comment]
@NoTaMu Yes I could look at that.  Could you make a separate issue please?

**Comment by bozdoz** [comment]
As this is a large issue, I will tackle this by adding more actions/filters to the code.  As it stands we've expanded markers to include many marker plugins; we can expand the map shortcode to work with other plugins on a one-by-one basis.  Please open a new, specific issue for each plugin you would like to be able to use. Thanks!
