### ISSUE TITLE
Marker adding does not work propperly

### ISSUE THREAD

**Issue by pmast** [bozdoz/wp-plugin-leaflet-map#4]
Hi there!

I inserted a map and a marker like this:
```
[leaflet-map height=300 width=500 lng=9.96927 lat=53.54685 zoom=16 zoomcontrol="1"]
[leaflet-marker lng=9.96927 lat=53.54685 msg="Message here: click here"]
```
However, I do not get in rendered correctly:
![leaflet_plugin](https://cloud.githubusercontent.com/assets/2733607/5719959/e5b3fc70-9b1d-11e4-859c-cef3674eeaf2.png)

I am using plugin version 1.9 and WP version 4.1

See also: http://www.aissummit.com/ais-summit-2015/venue

**Comment by bozdoz** [comment]
Not sure what issue you may be having.  I don't see any problems with your code.  Sorry for the late reply.

![screenshot from 2015-04-19 15 27 40](https://cloud.githubusercontent.com/assets/1410985/7220719/b6f61860-e6a8-11e4-96a4-d76565cfde35.png)

**Comment by pmast** [comment]
You merged my fix already.

I cannot remember anymore what the issue was. Apparently the fix I provided was fine.

Cheers!

Patrick

**Comment by bozdoz** [comment]
Yeah, I merged that because the guy who wanted image markers wasn't bothering me anymore.  But honestly I can't see how that would fix whatever issue you were having.  I'm guessing that the issue might have had to do with the attribute `msg` instead of `message`?
