### ISSUE TITLE
Stroke

### ISSUE THREAD

**Issue by valeriodeluca** [bozdoz/wp-plugin-leaflet-map#42]
I guys,
I don't know if is the right way to set bolor and stroke but seems it works fine. When I upload a geojson with correct value nothing appens if I change the stroke value or stroke-width.

For example I upload this sample record:

{
"type": "FeatureCollection",
"features": [
{ "type": "Feature", "properties": { "stroke": "#555555", "stroke-width": "1", "stroke-opacity": "1", "fill": "#70ffd2", "fill-opacity": "0.5", "popup-text": ".........

But if I set the plugin short code in this way:

[leaflet-geojson color="black" weight=0.5 src=http://www.mainjoin.eu/urbis/aeterna/istat/roma/roma_istat.geojson fitbounds=1 popup_property="popup-text"]

Setting stroke work. Work with many values like:
weight=2.0
weight=1.5
weight=1.0
weight=0.5
weight=0.3
weight=0.25
weight=0.1

And with lower stroke values the map loading is faster.
And with lower stroke values sometimes maps are more readable, I mean maps with many polygons.

I like to share my results :).

Best
Valerio

**Comment by bozdoz** [comment]
Hi Valerio:

Leaflet has a table of styling options on their website:

http://leafletjs.com/reference-1.0.3.html#path

`stroke-width` and `stroke-opacity` will **not** work.

Hope this helps

**Comment by bozdoz** [comment]
I assume this has been resolved.  Please re-open if there is more information.
