### ISSUE TITLE
Auto Centering Possible?

### ISSUE THREAD

**Issue by wplaunchify** [bozdoz/wp-plugin-leaflet-map#52]
I've implemented the plugin successfully at: https://www.campmenominee.com/map/

Is it possible to enable auto-centering on each leaflet popup when they are clicked?

Presently the behavior only seems to account for moving them horizontally enough to get them in screen, but not truly centered v/h.

_We're trying to emulate the behavior of this "native" leaflet implementation..so I believe it's possible: https://www.indianhead.com/facilities_

Thanks!

**Comment by bozdoz** [comment]
Super cool site.  Thanks for showing me.  

Looks like this should work for centering: https://stackoverflow.com/questions/22538473/leaflet-center-popup-and-marker-to-the-map

You might be able to overwrite the javascript, or I could try to implement this in a later version

**Comment by wplaunchify** [comment]
Right, saw that one! Just needed some help on how I might override the plugin defaults with that code? I'm a solid PHP guy, but a little rusty on .js ;-)

**Comment by bozdoz** [comment]
I would add an action to your functions.php file to enqueue a custom JavaScript file:

```php
add_action('leaflet_map_enqueue', 'my_enqueue');

function my_enqueue () {
	// get custom markercluster init script
	wp_enqueue_script('custom_script', get_template_directory_uri() . '/assets/js/leaflet-popup-center.js', Array('wp_leaflet_map'));
}
```

And in the `/assets/js/leaflet-popup-center.js` file (or whatever you name it), you could do this:

```javascript
if (window.WPLeafletMapPlugin) {
    // rename init function
    WPLeafletMapPlugin._init = WPLeafletMapPlugin.init;

    // create new init function, which calls renamed init
    WPLeafletMapPlugin.init = function() {
        WPLeafletMapPlugin._init();

        // now all maps have been initialized
        for (var i = 0, len = this.maps; i < len; i++) {
            // add popupopen event
            this.maps[i].on('popupopen', onPopupOpen, this.maps[i]);
        }

        function onPopupOpen (e) {
            var px = this.project(e.popup._latlng);
            px.y -= e.popup._container.clientHeight / 2;
            this.panTo(this.unproject(px), { animate: true });
        }
    };
}

```

**Comment by wplaunchify** [comment]
I greatly appreciate the help! ... 
Have implemented your suggestion, and seem to have the script properly enqueued.
However, it appears to have no effect on the ouput.
Would you have any other suggestions?
(I see no console errors or conflict, just no change in the centering)

**Comment by bozdoz** [comment]
Sorry I missed this.  I'm not sure what might have gone wrong.

**Comment by bozdoz** [comment]
Hoping this was sorted one way or another; if you have another issue open a new one. Thanks!
