### ISSUE TITLE
maxBounds implementation

### ISSUE THREAD

**Issue by NoTaMu** [bozdoz/wp-plugin-leaflet-map#53]
Would it be possible to have maxBounds implemented? I'm trying to make a local map with custom tiles and it seems like it would be really helpful.
Also, is it possible to assign a custom marker to a kml file?
Thank you very much for your time :)

**Comment by bozdoz** [comment]
I'll look into maxBounds.  The custom marker might be a bigger issue.

**Comment by bozdoz** [comment]
done with `[leaflet-map zoom=12 lat=51.05 lng=-114.06 maxbounds="50, -115; 52, -113"]`

**Comment by NoTaMu** [comment]
I have an issue with the maxbounds feature. It seems like the bounds array are getting printed before the map:
![captura de pantalla 2](https://user-images.githubusercontent.com/38410923/52070345-e6d0dc80-2580-11e9-81a8-e9caa0eed333.png)
