### ISSUE TITLE
Actions and filters Short Code

### ISSUE THREAD

**Issue by valeriodeluca** [bozdoz/wp-plugin-leaflet-map#55]
Graet 2.11 Change logs!
What Short Code I can use for Add actions and filters?
Thanks!

**Comment by bozdoz** [comment]
There's actions: `leaflet_map_loaded` and `leaflet_map_enqueue` for when the plugin is loaded, and when a map has finished enqueuing leaflet js and css.

There's also `leaflet_map_marker` filter, so you can change the marker constructor from `new L.Marker` to something custom (adding leaflet plugins for example).
