### ISSUE TITLE
Toggle fullscreen mode

### ISSUE THREAD

**Issue by bodograumann** [bozdoz/wp-plugin-leaflet-map#56]
First of all let me thank you for this great plugin. I was previously using “Google-Maps-GPX-Viewer” by Bernd Altmeier. Unfortunately that seems to be unmaintained but it also was never as polished as yours.

One feature that I really like to see is the possibility to cover the whole page with the map. The way I use leaflet-map, is to provide the readers with a smalish, floating preview map and if they want to explore the location in more detail they should be able to switch to a bigger view. Google-Maps-GPX-Viewer had a button in the upper right corner for that purpose:
![screenshot_20180616-110232](https://user-images.githubusercontent.com/1223583/41497391-b50b6200-7154-11e8-89ee-c332cd028c1c.png)

I would think something like that should not be too difficult. Maybe I will even have a stab at it myself if I can find the time.

**Comment by bozdoz** [comment]
When you say "whole page" do you mean full screen?

**Comment by bodograumann** [comment]
No. Well. The other plugin makes the map cover only the browser viewport. That would be desirable. But true fullscreen would be ok as well I guess.

**Comment by bozdoz** [comment]
K. Good to know.  I can look into this. Thanks!

**Comment by darthtaco** [comment]
Would love to see this too!  @bodograumann were you able to make any progress on this that you can share?

**Comment by bodograumann** [comment]
No, sorry, couldn’t find any time yet.
If there is more interest, I could bump the priority though :-D

**Comment by bodograumann** [comment]
There is no direct support in leaflet for a fullscreen mode, but I have tried this API: https://developer.mozilla.org/en-US/docs/Web/API/Element/requestFullscreen

I think it should work fine. Now we only need a button which makes the API call.

**Comment by bozdoz** [comment]
I'm still working on a better JavaScript API, but this can still be accomplished with the current version like so:

functions.php:
```php
add_action('leaflet_map_loaded', 'fs_leaflet_loaded');
function fs_leaflet_loaded() {
	wp_enqueue_script('full_screen_leaflet', 'https://api.mapbox.com/mapbox.js/plugins/leaflet-fullscreen/v1.0.1/Leaflet.fullscreen.min.js', Array('wp_leaflet_map'), '1.0', true);
	wp_enqueue_style('full_screen_leaflet_styles', 'https://api.mapbox.com/mapbox.js/plugins/leaflet-fullscreen/v1.0.1/leaflet.fullscreen.css');

	// custom js
	wp_enqueue_script('full_screen_custom', get_theme_file_uri( '/js/full-screen.js' ), Array('full_screen_leaflet'), '1.0', true);
}
```

in `/js/full-screen.js`
```js
function main() {
  if (!window.WPLeafletMapPlugin) {
    console.log('no plugin found!')
    return
  }

  var maps = window.WPLeafletMapPlugin.maps

  for (var i = 0, len = maps.length; i < len; i++) {
    var map = maps[i]
    map.whenReady(function() {
      this.addControl(new L.Control.Fullscreen())
    })
  }
}

window.addEventListener('load', main)
```

**Comment by bodograumann** [comment]
@bozdoz, Thank you that works for me.
I was even able to integrate the scale control.

```javascript
    map.whenReady(function() {
      this.addControl(new L.Control.Fullscreen({ position: 'topright' }));
      this.addControl(new L.Control.Scale({ position: 'bottomleft', metric: true, imperial: false }));
    })
```

**Comment by bozdoz** [comment]
I would recommend closing this issue now that there is a solution.  I've copied an implementation of this to the main README: https://github.com/bozdoz/wp-plugin-leaflet-map#how-can-i-add-another-leaflet-plugin
