### ISSUE TITLE
Add scale control option

### ISSUE THREAD

**Issue by nullbyte420** [bozdoz/wp-plugin-leaflet-map#57]
So the scale of the map can be easily visualised, like in google maps.

**Comment by bozdoz** [comment]
What does this mean?  Do you mean have a scale indicator of kilometers/miles?  Or do you mean zoom control buttons?

**Comment by nullbyte420** [comment]
Yes, a scale indicator!

**Comment by bozdoz** [comment]
I'll look into this.  Thanks.

**Comment by bozdoz** [comment]
https://leafletjs.com/reference-1.3.4.html#control-scale

**Comment by bozdoz** [comment]
my thoughts are that this could be an admin option, and a map option, similar to zoomcontrols.  

Something like:

`[leaflet-map scale=1]`
