### ISSUE TITLE
Add support for awesomeicons

### ISSUE THREAD

**Issue by nullbyte420** [bozdoz/wp-plugin-leaflet-map#58]
Hey, maybe add the awesome-markers leaflet plugin and refer to ionicons.com for an overview of the icons? Would be really great to have that included and selectable in a way like [leaflet-marker awesomeicon=train], for example.

This would fix #44 and #45 in a pretty and simple way. 

https://github.com/lvoogdt/Leaflet.awesome-markers

https://ionicons.com

**Comment by bozdoz** [comment]
There should already be support for ionicons, if you follow their instructions for Font Icon: https://ionicons.com/usage

Implementation would be:

```
[leaflet-marker svg="true" iconClass="icon ion-md-heart"]
```

**Comment by nullbyte420** [comment]
Hey, that's brilliant! Your implementation doesn't seem to work for me though, did you test it yourself?

**Comment by bozdoz** [comment]
I tested with Font Awesome.  See the test script implementation: https://codepen.io/bozdoz/pen/RMoKYN?editors=0010

You'd need to make sure you're adding the css for font-awesome, or ionicons in your case.

You can do this in your functions.php file, if you need:

```php
add_action('leaflet_map_enqueue', 'ionicons_enqueue');

function ionicons_enqueue () {
  wp_enqueue_style('ionicons', 'https://unpkg.com/ionicons@4.2.0/dist/css/ionicons.min.css');
}
```

**Comment by bozdoz** [comment]
Completely works as expected:

<img width="236" alt="screen shot 2018-07-02 at 10 39 26 pm" src="https://user-images.githubusercontent.com/1410985/42194122-d5f28cf4-7e48-11e8-9c4c-7ca9686c8cb7.png">
