### ISSUE TITLE
translation 's ready

### ISSUE THREAD

**Issue by berteh** [bozdoz/wp-plugin-leaflet-map#61]
plugin translation to french is ready at https://translate.wordpress.org/locale/fr/default/wp-plugins/leaflet-map
just needs to be accepted....
hope you can integrate it in next release.

**Comment by berteh** [comment]
bummer... no clue :/ are you logged in as the plugin owner? did someone else set up the wp plugin hosting for you ?

**Comment by berteh** [comment]
found how to on wordpress blog. I requested to be added as french translator for your project, will let you know.

**Comment by berteh** [comment]
I've been made FR editor for your plugin and reviewed the translations... you can now download the full file from  https://translate.wordpress.org/locale/fr/default/wp-plugins/leaflet-map , I guess.

**Comment by bozdoz** [comment]
Looks like it worked, yes?

**Comment by berteh** [comment]
yes. You just need now to integrate these translation files into your project code source.

**Comment by bozdoz** [comment]
I am unsure how to do this.  Nor can I find any information on this in the Translator's Handbook.  Any guidance?

**Comment by bodograumann** [comment]
You already have the necessary code in place afaics. So now you only need to put the `.mo` file into your languages directory.

**Comment by bozdoz** [comment]
@bodograumann where do I download the `.mo` file?

**Comment by bodograumann** [comment]
It seems I was mistaken. Here is detailed information:

https://cmljnelson.wordpress.com/2019/01/01/the-really-lazy-way-to-translate-a-wordpress-plugin/
https://make.wordpress.org/meta/handbook/documentation/translations/

So what I gather is:

The translation (for a specific language) needs to be 95% complete, then everything is loaded automatically. You don’t have to do anything else.

**Comment by bodograumann** [comment]
I'm now requesting becoming editor for the de locale.

It can be done here: https://make.wordpress.org/polyglots/

Here are the templates for how to write a request: https://make.wordpress.org/polyglots/handbook/rosetta/roles-and-capabilities/pte-request/#pte-request-by-a-plugintheme-author

**Comment by bodograumann** [comment]
I got confirmed as editor and have approved german translations. (Except for readme, which is not required). Let’s see if they find their way into my wordpress installation :-)

**Comment by bodograumann** [comment]
It worked! :fireworks: 
The admin menu entries are not translated, but apart from that everything is.
So I guess this issue can be closed.
