### ISSUE TITLE
adding lines

### ISSUE THREAD

**Issue by MannusEtten** [bozdoz/wp-plugin-leaflet-map#7]
i can put markers on the map with the plugin. really nice :-)

but i would like to describe the tour i did with my bike so i would like to draw a line on the map. is this possible as well?

**Comment by bozdoz** [comment]
@Remigr added line functionality.  I haven't pushed it to the svn repo, and made it available with the plugin yet.  Give me a couple days and I might have time.

**Comment by MannusEtten** [comment]
no problem, maybe i can even help you in the future with this plugin. thanks!
