### ISSUE TITLE
printr maxBounds?

### ISSUE THREAD

**Issue by leepeterson** [bozdoz/wp-plugin-leaflet-map#75]
Curious why the value of the maxBounds attribute is set to print.

I assumed that setting maxBounds could be used as an alternative to setting lat, lng, zoom, etc. Then there's no need to determine the map's center point (especially useful when plotting hundreds of markers within an arbitrary region).

But it appears that the array I pass to the attribute just prints it back out along with the rendered map below it.

https://github.com/bozdoz/wp-plugin-leaflet-map/blob/50c12fac6f341c187d1274d021c0a28cdb1aff2d/shortcodes/class.map-shortcode.php#L111

**Comment by bozdoz** [comment]
Looks like I wasn't finished testing this.  Didn't have it in either readme either. Thanks for the heads up!
