### ISSUE TITLE
GeoJSON: poor performance with many points

### ISSUE THREAD

**Issue by sal0max** [bozdoz/wp-plugin-leaflet-map#79]
Hi,

I want to show a map with as many as 1000 points, provided by a GeoJSON file. It works in general, but the performance is really poor, especially on low-end devices like phones.
Heres a topic on Stackoverflow regarding this and also a solution: https://stackoverflow.com/questions/43015854/

The solution, to use the [`pointToLayer`](https://leafletjs.com/reference-1.4.0.html#geojson-pointtolayer)-funtion to change regular [`Marker`](https://leafletjs.com/reference-1.4.0.html#marker)s to [`CircleMarker`](https://leafletjs.com/reference-1.4.0.html#circlemarker)s works quite well. I’ve tested it.

In `scripts/leaflet-ajax-geojson.js` this line

```js
this.layer = L.geoJson(null, this.options);
```

could be changed to something like this

```js
this.layer = L.geoJSON(null, {
    pointToLayer: function (feature, latlng) {
        return L.circleMarker(latlng, {
            radius: 7,
            fillColor: "#5080c6",
            color: "#fff",
            weight: 1,
            opacity: .75,
            fillOpacity: 1
        });
    }
});
```

Performance is no problem at all, now.
Of course one could let the plugin user chose what kind of markers should be shown and also let the circle markers make customizeable.

Is that a thing you would consider?

**Comment by bozdoz** [comment]
Absolutely.  I'm trying to make this plugin more extendable, and this would be a good option to have.  I'll have to give it some thought, but it's a great pick.

**Comment by bozdoz** [comment]
Related #64
