### ISSUE TITLE
On Using GPX files/External Files/WordPress Uploads

### ISSUE THREAD

**Issue by forteller** [bozdoz/wp-plugin-leaflet-map#81]
Hi. Thank you for an amazing plugin! It looks like exactly what I need.

Unfortunately I can't get it to work with the gpx file I have created with RideWithGPS. It works perfectly with the test gpx, but when I change the URL to my own it stops working.

Let me show you:
![Screenshot from 2019-03-29 16-56-49](https://user-images.githubusercontent.com/343561/55245790-2267ea00-5244-11e9-888a-f7af6422f862.png)

![Screenshot from 2019-03-29 16-56-29](https://user-images.githubusercontent.com/343561/55245801-2bf15200-5244-11e9-8bc5-d6a3be4dc975.png)

Here I have three maps. The one in the middle is using the default test gpx file shown in the shortcode help page. It works fine.

On the top map I've just switched the URL to my gpx file created with RWG. As you can see, it's not working. Just to make sure that it wasn't just the placing of the map that doesn't work I also created the bottom map where I have zoomed in to the area where the route should've been shown, but it's not there.

There are two types of gpx files you can create with RWG. This is the gpx track, not the gpx route. Here's the file: https://www.forteller.net/SLF/hjerterunden.gpx Also, directly from RWG: https://ridewithgps.com/routes/29477909.gpx?sub_format=track

Hope there's something you can do! If you need any more info just let me know.

Thank you so much again! :)

**Comment by forteller** [comment]
Now I tried it with a random gpx file I found online and uploaded to https://www.forteller.net/SLF/tysktest.gpx, and that didn't work either

**Comment by bozdoz** [comment]
Looks like it ought to work.  Here's what I tried (from the togeojson library: https://github.com/mapbox/togeojson):

```
> npm install -g @mapbox/togeojson
> wget https://www.forteller.net/SLF/hjerterunden.gpx
> togeojson hjerterunden.gpx > hjerterunden.json
> head hjerterunden.json
{
    "type": "FeatureCollection",
    "features": [
        {
            "type": "Feature",
            "properties": {
                "name": "Grønn rute Trondheim Hjerterunden 2. versjon"
            },
            "geometry": {
                "type": "LineString",
```

Could you share the URL for that test page of yours?

**Comment by forteller** [comment]
Thanks for the very fast reply!

Here's the page: https://blogg.forteller.net/kart-test/

**Comment by bozdoz** [comment]
You might have to copy that file from www.forteller.net to blogg.forteller.net, or enable CORS if you have access to the server config.  The browser is not allowing the file download:

<img width="630" alt="image" src="https://user-images.githubusercontent.com/1410985/55250407-dc535c00-522c-11e9-9575-fbf2f054c934.png">

Should work fine after either solution.  There may be some ajax solutions as well, but I'm less familiar/confident with those.

**Comment by forteller** [comment]
Thank you! I tried it now, but no luck. Same URL as above.

**Comment by bozdoz** [comment]
Getting 404: https://blogg.forteller.net/wp-content/uploads/2019/SLF/hjerterunden.gpx

File does not exist?

**Comment by forteller** [comment]
That's crazy. I get the same 404, but it's there in my FTP client:
![Screenshot from 2019-03-29 19-31-00](https://user-images.githubusercontent.com/343561/55254843-45e95f80-5259-11e9-978a-83aca7609ab1.png)

And anyways I don't understand why it wouldn't work from forteller.net, when the default test gpx, which is hosted on a totally different server, works fine…

**Comment by bozdoz** [comment]
Depends on the server; for example, github would allow requests from any server, but your server by default does not allow it.

Very likely this is now either your web server denying the request or WordPress itself.  I believe the uploads directory only allows some file types.  Maybe you could put the file in the root, or some other custom directory (`/data` for example).  

To allow additional file types, it looks like you could try something described here: https://neliosoftware.com/blog/how-to-upload-additional-file-types-in-wordpress/

**Comment by bozdoz** [comment]
for example, in functions.php:

```php
add_filter( 'upload_mimes', 'my_myme_types', 1, 1 );

function my_myme_types( $mime_types ) {
    $mime_types['gpx'] = 'application/gpx+xml'; 
    return $mime_types;
}
```

Then you should be able to use gpx files in your uploads.

**Comment by forteller** [comment]
I was totally stupid and uploaded everything to the wrong place! Everything works fine, thank you for all the help! Sorry for being a dumbass!
