### ISSUE TITLE
file_get_contents geocoding does not work

### ISSUE THREAD

**Issue by bodograumann** [bozdoz/wp-plugin-leaflet-map#82]
I did previously not have the curl extension installed on my server, so the geocoder `get_url` method used `file_get_contents`.

It seems that does not work, at least with the osm geocoder. When trying it manually from the php cli, I get status code 403, forbidden back.

**Comment by bozdoz** [comment]
Probably related to the requirements of usage of Nominatim:  https://operations.osmfoundation.org/policies/nominatim/#requirements

Namely: 

> Provide a valid HTTP Referer or User-Agent

I believe curl only works with this:

```php
curl_setopt($ch, CURLOPT_REFERER, get_site_url());
```

**Comment by bodograumann** [comment]
Then maybe for the other method the referrer should be set as well. This might be the way:
https://stackoverflow.com/a/2107792/1534459

**Comment by bozdoz** [comment]
Looks like that works great! Thanks!
