### ISSUE TITLE
Shortcode generator does not work

### ISSUE THREAD

**Issue by bodograumann** [bozdoz/wp-plugin-leaflet-map#84]
When using the shortcode generator in the administration panel, no shortcode is displayed.
Unfortunately I was not able to determine the cause, but it seems like the `move` and `drag` eventhandlers are not called in `shortcode-helpers.js`.
The browser console shows the following error, when loading the page:

```
TypeError: t is null[Weitere Informationen] leaflet.js:5:81149
    _projectLatlngs https://unpkg.com/leaflet@latest/dist/leaflet.js:5
    _projectLatlngs https://unpkg.com/leaflet@latest/dist/leaflet.js:5
    _projectLatlngs https://unpkg.com/leaflet@latest/dist/leaflet.js:5
    _project https://unpkg.com/leaflet@latest/dist/leaflet.js:5
    _reset https://unpkg.com/leaflet@latest/dist/leaflet.js:5
    onAdd https://unpkg.com/leaflet@latest/dist/leaflet.js:5
    _layerAdd https://unpkg.com/leaflet@latest/dist/leaflet.js:5
    whenReady https://unpkg.com/leaflet@latest/dist/leaflet.js:5
    addLayer https://unpkg.com/leaflet@latest/dist/leaflet.js:5
    addLayer https://unpkg.com/leaflet@latest/dist/leaflet.js:5
    addLayer https://unpkg.com/leaflet@latest/dist/leaflet.js:5
    addTo https://unpkg.com/leaflet@latest/dist/leaflet.js:5
    <anonym> https://█████████/wp-admin/admin.php?page=leaflet-shortcode-helper:1684
    init https://█████████/wp-content/plugins/leaflet-map/scripts/construct-leaflet-map.min.js?ver=2.14.0:1
```

**Comment by bozdoz** [comment]
I have tested 2.14.0, loading the admin shortcode generator page with the minified script and the source script, and neither fails.  Is there anything else I can try to reproduce this error?

**Comment by bodograumann** [comment]
Maybe this is some compatibility issue with the theme / other plugins. Guess I have to investigate further myself.

**Comment by bodograumann** [comment]
I have narrowed down the issue. It is caused by one of the examples. Removing the following will fix it for me:

```php
__("More Crazy Line Attributes", 'leaflet-map') => array(
    '[leaflet-map fitbounds]',
    '[leaflet-line color="red" weight=10 dasharray="2,15" addresses="Halifax, Nova Scotia; Tanzania" classname=marching-ants]'
    )
```

I should have seen this earlier, because all examples after this one are not rendered.

The problem is that the `leaflet-line` shortcode with the addresses is generating the following javascript statement:

```javascript
line = L.polyline([[null,null],[0,0]], {"color":"red","weight":10,"dashArray":"2,15","className":"marching-ants"})
```

Leaflet is not very robust when handling the `Latlng` with value `[null, null]`, so it breaks down there.

**Comment by bozdoz** [comment]
Ah, it's doing that because of the geocoder I imagine.  Wonder if it would help clearing your geocoder cache in the leaflet defaults page.  I can try to fix that possible issue too.

**Comment by bodograumann** [comment]
Hahaha, clearing the geocoder cache actually worked as well.
I actually cleared it before when debugging the geocoder issue, but that was on a child site in my wordpress network.
Now I was working on the main site where I didn’t do it :-D

I still feel like the geocoder failing should not break something completely unrelated. I just can not say at which point the cascade needs to be broken.
