### ISSUE TITLE
Add Gutenberg Block

### ISSUE THREAD

**Issue by bodograumann** [bozdoz/wp-plugin-leaflet-map#87]
I think it would be great to have a Gutenberg block which is based on the shortcode generator.

**Comment by bozdoz** [comment]
I looked into this a bit, and I'm not sure exactly how it should work.  Any thoughts?

**Comment by bodograumann** [comment]
My idea was this:
- The users can add leaflet blocks in the gutenberg editor. When they do that,
- there is an interactive map in the editor (similar to the existing shortcode generator) where they can select a view / point of the map.
- They can toggle / check what features they want. E.g. a map marker.
- In the actual article the map is displayed with the selected features.

**Comment by bozdoz** [comment]
I looked into this a few times, and so far I have found Gutenberg block development to be difficult.  More difficult than maintaining this plugin in the first place!  Really cool idea but possibly out of my range in terms of time/experience

**Comment by Ambrosiani** [comment]
there's a [block available](https://wordpress.org/plugins/map-block-leaflet/) (with fewer options) – maybe something can be included from that plugin. A bit above my wp level as well unfortunately :/

**Comment by bozdoz** [comment]
I kind of hate gutenberg blocks.  I have a hard time believing I'd accept a PR for this.  At the moment, I think I'll have to close this feature request
