### ISSUE TITLE
Ghostly lines within a wordpress page

### ISSUE THREAD

**Issue by ghisabrain** [bozdoz/wp-plugin-leaflet-map#88]
Hello Everybody!

I am just new in GitHub and this is my first issue posted!

My problem is that I am trying to include like 24 markers within a map.
Following the instructions given with this plugin I inserted a shortcode in an empty page like this:
[leaflet-map zoom=16 lat=43.77136 lng=11.25527 height="400"]

Just after (in the same block) I added 24 Markers like this:

[leaflet-marker  lat=43.77299 lng=11.25600]
(1) Florence Cathedral, Cattedrale di Firenze
[/leaflet-marker]

[leaflet-marker  lat=43.77316 lng=11.25520]
(2) Saint John Baptistery, Battistero di San Giovanni
[/leaflet-marker]

[leaflet-marker  lat=43.77313 lng=11.25531]
(3) Heaven's Gate, Porta del Paradiso
[/leaflet-marker]

....
...
Etc..

The result is that in this page, which I remark has just the map (in one block), delivers correctly the Map with all the markers in the right place but below the map there are as many empy lines of text as much are the markers. If remove the markers these empty lines disappear.
As I want to add another block following the map how can I get rid of the empty lines of text?
Am I doing something wrong?

Thank you so much for the help. Your plugin is fantastic and simple to use.

**Comment by ghisabrain** [comment]
Ok, I found the solution with minimum effort. 
At least in my case the solution was to place map shortcode and markers short code in two different blocks. By doing so the empty lines of text disappear. Maybe it is obvious, I do not know but i this way everything work as expected. Great job with this plugin!

**Comment by bozdoz** [comment]
Great! Thanks for the follow up! Closing this issue now.
