### ISSUE TITLE
togeojson.js (from Mapbox)

### ISSUE THREAD

**Issue by sal0max** [bozdoz/wp-plugin-leaflet-map#90]
Checking my page for GDPR compliancy I noticed that this plugin loads a file from a third party server (https://cdn.rawgit.com/mapbox/togeojson/master/togeojson.js), caused because of this:
https://github.com/bozdoz/wp-plugin-leaflet-map/blob/0bcd7192206251000200a2ba46dd243507464063/class.leaflet-map.php#L200

Two problems with it:

1. This is not really GDPR compliant, as far as I know.
2. https://cdn.rawgit.com will shut down in the near future (October 2019). Click the link for details.

Instead this Plugin should bundle the file. Mapbox is even encouraging it, as stated in their [README.md](https://github.com/mapbox/togeojson#browser).

**Comment by bozdoz** [comment]
Good points. 

What do you think about changing the request to unpkg CDN?  Note that the site's host has pointed out that it does not "collect, process, or store any personal information", so it is GDPR compliant. 

Sidenote: I'd prefer not to have other plugins bundled in this plugin.

**Comment by sal0max** [comment]
The switch to unpkg seems reasonable, if you take into account that by default this plugin loads `leaflet.css` and `leaflet.js` from there, too. Would definitely be consistent.
Even more consistent would be, if you'd make `togeojson.js` configurable, like the two leaflet-files.

Regarding GDPR:
I'm really no law expert. But most of the information I found regarding embedded resources (like libraries from CDNs) are a problem. An IP address is considered private data and by linking external resources I, as a website operator, give this private data to a third party (the CDN provider). A simple statement on Twitter that unpkg doesn't collect any data doesn't seem (legally) sufficient to me.

So, I think the best way indeed would be to at least use a consistent cdn: unpkg.
**But most importantly: In order to give the plugin user the chance to get GDPR compliancy, make every external dependency configurable.**

**Comment by bozdoz** [comment]
I like that idea.
