### ISSUE TITLE
Leaflet shortcodes + ajax posts = non unique container IDs

### ISSUE THREAD

**Issue by WAMH** [bozdoz/wp-plugin-leaflet-map#91]
Good day,

I am using your plugin on a WP site where posts are called via ajax. When the new calls come in, the IDs that leaflet generates for the map containers gets reset and starts again (generated_id_1, generated_id_2, generated_id_3 / AJAX CALL new posts: / generated_id_1...)

This causes an error that I've seen people ask about and not finding solutions: 

> Uncaught Error: Map container is already initialized

Is there a way to force an ID from the shortcode? Otherwise this bug would need to be solved in the plugin / the library (must thoroughly check the DOM for existing IDs and start the suffix increment after the highest id_NUMBER).

Hope this makes sense and helps people out there.

**Comment by bozdoz** [comment]
Might make sense.  I'm still unsure how the id's get reset.  How are you getting posts via ajax?  Is there a php example or a plugin you can show me so I can test?

**Comment by sal0max** [comment]
This fix is probably the cause for a new problem.

Since some time I notice that my rss reader marks one post of my website unread/new after each refresh. It's the one post which contains a leaflet map.
The reader (tt-rss) generates the sha1-hash of the content of each rss entry to see if somethin has changed. If yes, it marks it unread/new:

```
[11:19:29/12411] done collecting data.
[11:19:29/12411] article hash: 5b6974d9bff6cd30e90f754dd1f46426a98c5e5c [stored=0b21493a3214292586dd4e1a13aeb4619622b215]
[11:19:29/12411] hash differs, applying plugin filters:
```

The hash always differs, as the id `leaflet-map-...` changes with each request:
```xml
<content type="html" [...] <p> <div id="leaflet-map-298c858298a11" class="leaflet-map" style="height:50vh; width:100%;"></div> [...]
</content>
```

I don't really understand what the original problem of @WAMH seems to be, but maybe there is a compromise for both issues?

**Comment by bozdoz** [comment]
That's an interesting problem.  Perhaps I can add an option to have auto-incremented or randomized id's.  Thoughts?

**Comment by bozdoz** [comment]
Agreed on the configurability (it's already too high).  I added it because it did not appear to me to matter; and, as stated above, the primary issue was rendering the posts via ajax, which perhaps obviously wasn't aware of the other ids.

**Comment by sal0max** [comment]
I understand the recent change from counting id to random id.
But I'm asking myself if ids are required in general. Maybe just remove them completely?

**Comment by bozdoz** [comment]
I suppose I could pass the HTMLElement instead.

**Comment by bozdoz** [comment]
Not sure how, at first glance.  Looks like I have to put some kind of placeholder there in HTML. Not yet sure how I would create the element in JS (and place it properly in the DOM).

**Comment by bozdoz** [comment]
Might have it.  I'll post a PR

**Comment by sal0max** [comment]
> Not sure how, at first glance. Looks like I have to put some kind of placeholder there in HTML. Not yet sure how I would create the element in JS (and place it properly in the DOM).
Blame on me. I didn't read the Leavlet Docs up to now and didn't know that it wants to either have an id or HTMLElement upon creation.

> Might have it. I'll post a PR
Curious about it! :)

**Comment by sal0max** [comment]
Just found the time to try it out. Works like a charm, for me. :)
Great!
