### ISSUE TITLE
How to change location at the press of a button?

### ISSUE THREAD

**Issue by web02upctax** [bozdoz/wp-plugin-leaflet-map#98]
I have 2 buttons, I need that when one is pressed it shows one location and when I press the other it shows another different location

**Comment by bozdoz** [comment]
I would add some JavaScript to the page.  I created a test page, then created a template for that page, then added some javascript to the page:

Test Page Content:
```
[leaflet-map address="toronto"]
[leaflet-marker address="toronto"]Toronto[/leaflet-marker]
[leaflet-marker address="montreal"]Montreal[/leaflet-marker]
```

Script at the bottom of my [Page Template](https://developer.wordpress.org/themes/template-files-section/page-template-files/)
```js
<script async defer>
(function() {
    function main() {
        // get the first map
        var map = window.WPLeafletMapPlugin.maps[0]
        // get all markers in first map
        var group = window.WPLeafletMapPlugin.markergroups[1]
        var markers = group.getLayers()

        for (var i = 0, len = markers.length; i < len; i++) {
            var marker = markers[i]
            createButton(marker)
        }

        function createButton (marker) {
            // try to get popup
            var content
            try {
                content = marker._popup._content
            } catch (e) {
                content = "Marker " + (i + 1)
            }

            // add button
            var button = document.createElement('button')
            button.innerText = content
            var map = marker._map
            var container = map._container

            container.parentNode.insertBefore(button, container.nextSibling)

            button.addEventListener('click', function () {
                map.flyTo(marker.getLatLng(), map.getZoom(), {
                    duration: 0.8
                })
            })
        }
    }

    function waitForMap () {
        var map
        try {
            map = window.WPLeafletMapPlugin.maps[0]
        } catch (e) {
            // pass
        }
        if (map) {
            main()
        } else {
            setTimeout(waitForMap, 100)
        }
    }

    window.addEventListener('load', waitForMap)
})();
</script>
```

And here's the result:

<img width="344" alt="image" src="https://user-images.githubusercontent.com/1410985/73760459-b697bd00-4743-11ea-85f0-e3e2cd4f110e.png">

**Comment by Simbaclaws** [comment]
How does this change the position of the marker though? You're just creating 2 markers and fly to the other one when you click the button.

Suppose I have a script where I want to add a marker dynamically to the map and change it's position based on a subscription to an API. How can I achieve this? 
I console logged window.WPLeafletMapPlugin
and couldn't find any way to add a marker to a map or to change it's location.

If I can't achieve this with your plugin I'll sadly have to find a plugin that does, or create it myself with leaflet.js. (Which is not ideal when using wordpress for the customer)
Or perhaps create a pull request to your project where I create this functionality myself.
